-- CreateTable
CREATE TABLE "Presenca" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "pessoaID" INTEGER NOT NULL,
    "areaID" INTEGER NOT NULL,
    "dataHora" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Presenca_pessoaID_fkey" FOREIGN KEY ("pessoaID") REFERENCES "Pessoa" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "Presenca_areaID_fkey" FOREIGN KEY ("areaID") REFERENCES "Area" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
